
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: weather-api-production-service
          servicePort: {{ .Values.ingress.port }}